# Generated by Django 5.2.3 on 2025-06-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equipment/', verbose_name='صورة الجهاز')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف مختصر')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
            ],
            options={
                'verbose_name': 'صورة جهاز',
                'verbose_name_plural': 'صور الأجهزة',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العرض')),
                ('description', models.TextField(verbose_name='وصف العرض')),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='صورة العرض')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
            },
        ),
    ]
