# Generated by Django 5.2.3 on 2025-06-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_equipmentimage_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='رابط انستجرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='شعار الموقع'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='رابط واتساب'),
        ),
    ]
